[workspace]
members = [
    "liblisa-core",
    "liblisa-enc",
    "liblisa-synth",
    "liblisa",
    "liblisa-x64",
    "liblisa-x64-kmod",
    "liblisa-x64-kmod/kmodtest",
    "lisacli",
]

[profile.dev]
opt-level = 1

[profile.release]
lto = "fat"
debug = true